### ISSUE TITLE
new issues about parallel

### ISSUE THREAD

**Issue by armgong** [armgong/rjulia#13]
https://github.com/JuliaLang/julia/issues/10085,it happens on julia 0.35 ,but not on 0.33 and 0.4 
@mmaechler could you see two different r code? and verify following code on your julia 0.4 is ok? 

1:following code can't run on julia 0.35
~~~r
library(rjulia)
julia_init()
julia_eval("addprocs(1)")
for (i in 1:2)
{
 julia_void_eval(paste("r=remotecall(",i,", rand, 2, 2)",sep = ""))
 y <- j2r(" fetch(r)")
 cat("\n")
 cat("process", i, "got value:\n"); print(y)
}
julia_void_eval("rmprocs(workers())")
~~~
2 but if change code to this, it just ok,why this happends?
~~~r
library(rjulia)
julia_init()
julia_eval("addprocs(1)")
julia_void_eval("r=remotecall(1, rand, 2, 2)")
y <- j2r(" fetch(r)")
y
julia_void_eval("r=remotecall(2, rand, 2, 2)")
y <- j2r(" fetch(r)")
y
julia_void_eval("rmprocs(workers())")
~~~

**Comment by armgong** [comment]
this code also failed on julia 0.35
~~~r
library(rjulia)
julia_init()
julia_eval("addprocs(1)")
x<-c("r=remotecall(1, rand, 2, 2)","r=remotecall(2, rand, 2, 2)")
for (i in 1:2)
{
  julia_void_eval(x[i])
  y <- j2r("fetch(r)")
  cat("\n")
  cat("process", i, "got value:\n"); 
  print(y)
}
julia_void_eval("rmprocs(workers())")

**Comment by mmaechler** [comment]
@armgong : Was the code that fails in 3.5  running ok earlier, i.e., before my changes to `RJulia`?
Honestly, I have not looked into the whole parallel parts and issues, and am not knowledgable enough about julia to even try to see what exactly `remotecall()` should do.
Apropos: Any chance that   `j2r("fetch(r)")`  could be simplified into `j2r("r")`?  I would prefer that and it seems not hard to do the change on the R end.

**Comment by armgong** [comment]
this issue is caused by ***julia*** commit 06d01c2c773d6c4a2c44cdd809d541585ae489de , revert it will fix,but we need wait julia dev revert the commit.
and @mmaechler  thank you for your modify demo and write help

**Comment by armgong** [comment]
this issue maybe will not solve by julia dev, so if anyone want avoid this issue. please use rjulia 0.4 branch  which support julia 0.4 dev

**Comment by armgong** [comment]
julia 0.4 release, 0.4 branch of rjulia will be master, so close this issue
