### ISSUE TITLE
Installing rjulia on Ubuntu 15.04, R 

### ISSUE THREAD

**Issue by simone66b** [armgong/RJulia#18]
I can't get rjulia to install on my Ubuntu machine. I am running Ubuntu 15.04, julia 0.3.10 (compiled from source) and the latest R (see below) Here is the error message:

devtools::install_github("armgong/RJulia", ref="master", args = "--no-multiarch")#
Downloading github repo armgong/RJulia@master
Installing rjulia
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore CMD  \
  INSTALL '/tmp/RtmpWOv9ki/devtoolsa4967e9937d/armgong-RJulia-45f6ac1'  \
  --library='/usr/local/lib/R/site-library' --install-tests --no-multiarch 

* installing *source* package ‘rjulia’ ...
** libs
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG -I"/usr/bin"/../../src -I"/usr/bin"/../../src/support -I"/usr/bin"/../include -I"/usr/bin"/../include/julia     -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c Julia_R.c -o Julia_R.o
Julia_R.c:11:19: fatal error: julia.h: No such file or directory
 #include <julia.h>
                   ^
compilation terminated.
/usr/lib/R/etc/Makeconf:134: recipe for target 'Julia_R.o' failed
make: *** [Julia_R.o] Error 1
ERROR: compilation failed for package ‘rjulia’
* removing ‘/usr/local/lib/R/site-library/rjulia’
Error: Command failed (1)

Julia info:

Julia Version 0.3.10
Commit c8ceeef (2015-06-24 13:54 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU           X5690  @ 3.47GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

R info:
                                     sysname 
                                     "Linux" 
                                     release 
                          "3.8.0-32-generic" 
                                     version 
"#47-Ubuntu SMP Tue Oct 1 22:35:23 UTC 2013" 
                                    nodename 
                           "biol-blomber02d" 
                                     machine 
                                    "x86_64" 
                                       login 
                                    "simonb" 
                                        user 
                                      "root" 
                              effective_user 
                                      "root"

**Comment by armgong** [comment]
please check julia.h whether  in  your /usr/include/julia/ ? 
rjulia assume julia header file in  JULIA_HOME/../include/ or JULIA_HOME/../include/julia/ ,and in your system JUALIA_HOME is /usr/bin ,so header file need in /usr/include or /usr/include/julia.

maybe  forgot install  julia header file to /usr/include or /usr/include/julia ? 

btw:
on linux install rjulia please use  
devtools::install_github("armgong/RJulia", ref="master")

only on windows need  
devtools::install_github("armgong/RJulia", ref="master", args = "--no-multiarch")

**Comment by simone66b** [comment]
OK. It seems that compiling from source doesn't put the header files where Ubuntu would like them to be. I installed from the .deb package and then successfully installed rjulia. Thanks!
