### ISSUE TITLE
Use Vector{Any} in R_Julia_MD for R list?

### ISSUE THREAD

**Issue by phaverty** [armgong/rjulia#31]
The code for converting an R list to a julia type is pretty complicated due to the current trouble of creating tuples from C.  Perhaps an R list could be represented as Vector{Any} rather than as a tuple? That would be much simpler and allow the object to be used in the same way R uses lists.

**Comment by armgong** [comment]
convert to Vector{any} is better way than to a tuple, I will try it next week. thanks
