### ISSUE TITLE
speedier TransArrayToDataArray?

### ISSUE THREAD

**Issue by phaverty** [armgong/rjulia#33]
jl_eval_string seems to be one of the slower bits of the julia C API.  One might be able to do a version of TransArrayToDataArray that uses jl_get_function and jl_call2.  [This discussion](https://groups.google.com/forum/#!msg/julia-users/-_nGAynvYI8/a7NzQblPsM8J) seems to offer the solution. I experimented a bit and have not yet been successful getting a pointer to DataArrays.DataArray (and/or the DataArrays module), but I think it should be possible.
Compiling on Mac gives a number of warnings related to snprintf, so this alternate strategy would have a nice side effect of removing those warnings.

**Comment by armgong** [comment]
last year, I try this in https://github.com/armgong/rjulia/blob/nextgen/src/R_Julia.c on julia 0.3 , but the speed not improve so much, maybe the situation change now, you can try again.

**Comment by armgong** [comment]
I modify the comment on github ,so please don't read the comment in mail, it will not send the modified message to email

**Comment by phaverty** [comment]
I like your idea of using the logical array from R generated by is.na and just copying it to julia. That would simplify the rjulia code a lot. It might have to be copied in a loop with a cast as R logicals are int32 and julia bools are int8, right?  Still, that would be dramatically simpler!

**Comment by armgong** [comment]
I think maybe we could  avoid use loop by create a julia int32 array , memcopy R array ,convert julia int32 array to int8 array.
~~~julia
julia> X=Array(Int32,10)
10-element Array{Int32,1}:
 -2048134640
           0
 -2048134576
           0
 -2048134512
           0
 -2046260688
           0
 -2048131984
           0

julia> for i in 1:10
        X[i]=i
       end

julia> convert(Array{Int8},X)
10-element Array{Int8,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

julia>
~~~

**Comment by armgong** [comment]
sorry DataArray.na is BitArray not Array{Int8},so we need convert like this
~~~julia
julia> convert(BitArray,X)
10-element BitArray{1}:
 true
 true
 true
 true
 true
 true
 true
 true
 true
 true
~~~

**Comment by armgong** [comment]
or use
~~~julia
julia> BitArray(X)
10-element BitArray{1}:
 true
 true
 true
 true
 true
 true
 true
 true
 true
 true
~~~

**Comment by phaverty** [comment]
Great, maybe we can call BitArray on the Int32 array when we construct the
DataArray:

data_array = DataArrays.DataArray( data_array, BitArray(int32_vector) )

?

Pete

____________________
Peter M. Haverty, Ph.D.
Genentech, Inc.
phaverty@gene.com

**Comment by phaverty** [comment]
I have an implementation of these ideas, based on your 0.5 branch over at https://github.com/phaverty/rjulia

Specifically, I use jl_get_function to look up functions and then call them with jl_call2 (etc.). This results in simpler code. I haven't compared the speed yet. (I wonder if the function lookup can be made static so we just pay for that once?).

As part of this, I moved the association of C-level objects with julia global namespace symbols to the top level functions. This allows for functions like R_Juila_MD_NA to be used other places, like in DataFrame creation. Please let me know if you like that change or not.

The current state is that the code for 'r2j' works. I believe my copy of 'j2r' needs some more work.

**Comment by phaverty** [comment]
The relevant updates have been committed. Closing.
