### ISSUE TITLE
Install on linux fails: julia-config.jl: No such file or directory

### ISSUE THREAD

**Issue by vh-d** [armgong/rjulia#47]
I am getting 
```
/bin/bash: /usr/bin/../share/julia/julia-config.jl: No such file or directory
```
during installation on Linux via

```
devtools::install_github("armgong/rjulia", ref="julia0.5")
```

The file julia-config.jl actually does not even seem to exist on my machine.

**Comment by armgong** [comment]
standard installed julia should have the julia-config.jl file. or you can download the file from julia repo

**Comment by vh-d** [comment]
You are right. It is present in the generic linux tarball but not in the Ubuntu customized binary package. I will contact the maintainer of the package.

Copying julia-config.jl to /usr/share/julia solves the problem for now.
